### ISSUE TITLE
defaultParams

### ISSUE THREAD

**Issue by PabloPG** [avanti/avanti-search#19]
Olá,

Estou usando o plugin de vocês, que por sinal ajudou muito, porém a parte de ordenação não está funcionando, ele passa a query na url de busca porém o retorno dos itens não vem paginado, sabe como resolve?

**Comment by carloschneider** [comment]
@PabloPG Pode passar como você está chamando o plugin?

**Comment by PabloPG** [comment]
`$resultItems = $('.resultItemsWrapper div[id^="ResultItems"]');
	$('.resultItemsWrapper div[id^="ResultItems"]').avantiSearch({
		defaultParams: {
			'query': {
			  	'O': 'OrderByPriceASC'
			}
		}
	});`

A url passa corretamente,  api/catalog_system/pub/products/search?fq=C:/1/&PS=8&sl=19ccd66b-b568-43cb-a106-b52f9796f5cd&cc=8&sm=0&PageNumber=1O=OrderByPriceASC

**Comment by carloschneider** [comment]
@PabloPG Não entendi muito bem a sua dúvida, consegue me explicar um pouco melhor? Você está com problema na paginação?

**Comment by PabloPG** [comment]
O problema é proveniente da VTex... pode fechar.
